# Generated by Django 2.2.1 on 2019-08-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='involvedactive',
            name='member_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='program',
            name='member_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='tutoractive',
            name='member_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
    ]
