# Generated by Django 2.2.1 on 2019-09-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_subscribepresentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='summary',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='involvedactive',
            name='summary',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='program',
            name='summary',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='tutoractive',
            name='summary',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
