# Generated by Django 2.2.1 on 2019-09-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190917_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeractive',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registeractive',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registeractive',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registeractive',
            name='phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
