# Generated by Django 2.2.1 on 2019-10-09 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
