# Generated by Django 2.2.1 on 2019-10-10 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20191009_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('event_name', models.CharField(max_length=200)),
                ('number', models.IntegerField(default=1)),
                ('register_date', models.DateField(default=datetime.date.today)),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
    ]
