# Generated by Django 2.2.1 on 2019-10-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_signupproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupproject',
            name='first_choice',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='signupproject',
            name='second_choice',
            field=models.CharField(max_length=200),
        ),
    ]
